// List of Nigerian banks including digital banks with their codes

export const NIGERIAN_BANKS = [
  { name: "Access Bank", code: "044" },
  { name: "Citibank Nigeria", code: "023" },
  { name: "Ecobank Nigeria", code: "050" },
  { name: "Fidelity Bank", code: "070" },
  { name: "First Bank of Nigeria", code: "011" },
  { name: "First City Monument Bank (FCMB)", code: "214" },
  { name: "Guaranty Trust Bank (GTB)", code: "058" },
  { name: "Heritage Bank", code: "030" },
  { name: "Keystone Bank", code: "082" },
  { name: "Polaris Bank", code: "076" },
  { name: "Stanbic IBTC Bank", code: "221" },
  { name: "Standard Chartered Bank Nigeria", code: "068" },
  { name: "Sterling Bank", code: "232" },
  { name: "Union Bank of Nigeria", code: "032" },
  { name: "United Bank for Africa (UBA)", code: "033" },
  { name: "Unity Bank", code: "215" },
  { name: "Wema Bank", code: "035" },
  { name: "Zenith Bank", code: "057" },
  { name: "Jaiz Bank", code: "301" },
  { name: "MoniePoint", code: "303" },
  { name: "Providus Bank", code: "101" },
  { name: "Suntrust Bank", code: "100" },
  { name: "OPay", code: "304" },
  { name: "PalmPay", code: "305" },
  { name: "Kuda Bank", code: "306" },
  { name: "Rubies Bank", code: "307" },
  { name: "Sparkle Microfinance Bank", code: "308" },
  { name: "Mint Finex MFB", code: "309" },
  { name: "VFD Microfinance Bank", code: "310" },
  { name: "FinaTrust Microfinance Bank", code: "311" },
  { name: "FairMoney Microfinance Bank", code: "312" }
];
